mat1 <- matrix(1:20, nrow = 5, ncol = 4, byrow = TRUE,dimnames = list(paste("R",1:5), paste("C",1:4)))
print(mat1)
mat2 <- matrix(1:9, nrow = 3, ncol = 3, byrow = FALSE,dimnames = list(paste("R",1:3), paste("C",1:3)))
print(mat2)
mat3 <- matrix(1:4, nrow = 2, ncol = 2, byrow = TRUE,dimnames = list(c("Row1","Row2"), c("Col1","Col2")))
print(mat3)